import os
import sys
import struct
import io
import zipfile
import csv

# ==============================================================================
# GTFO REPLAY BINARY PARSER & DATA SCRAPER
# ==============================================================================
# This script decompresses and parses GTFO replay binary files (.compressed)
# generated by the GTFOReplay mod. It extracts StatTracker data (Damage, Kills, 
# Packs used, Revives, Tongue Dodges) and exports them into a structured CSV file 
# with metadata headers.
# 
# Replay File Format Architecture:
# --------------------------------
# A GTFO replay file consists of:
# 1. Combined Header Size (4-byte int)
# 2. Typemap: Maps runtime type IDs (ushort) to typename & version strings.
# 3. Headers: Static level elements (doors, terminals, generators, metadata) 
#    terminated by "ReplayRecorder.EndOfHeader".
# 4. Snapshot Loop: Sequential blocks (each starting with a 4-byte int size)
#    representing discrete gameplay ticks (10 or 20 ticks/sec).
#    Each snapshot contains:
#      a. Timestamp: Milliseconds since startup (4-byte uint).
#      b. Events: Discrete actions (Damage, PackUse, Spawns, Despawns) containing 
#         millisecond deltas.
#      c. Dynamics: Ongoing entities (movement, stats) - which we can safely skip 
#         using snapshot sizing!
# ==============================================================================

# Standard enemy health lookups from GTFO Game Database for backwards compatibility
# when version 0.0.1 Vanilla.Enemy is in use (which did not serialize maxHealth).
BACKWARDS_COMPAT_ENEMY_HP = {
    0: float('inf'),
    20: 42,
    40: 42,
    41: 60,
    21: 20,
    35: 120,
    38: 5,
    48: 5,
    63: 5,
    13: 20,
    31: 20,
    32: 20,
    24: 20,
    49: 20,
    16: 120,
    28: 120,
    50: 120,
    26: 30,
    51: 30,
    11: 30,
    18: 150,
    33: 150,
    30: 30,
    39: 120,
    29: 1000,
    36: 1000,
    37: 2500,
    55: 5000,
    46: 225,
    47: float('inf'),
    42: 16.2,
    45: 150,
    43: 6000,
    44: 6000,
    53: 37,
    52: 18,
    54: 42,
    56: 161,
    62: 640
}

class BinaryReader:
    """
    A utility class to decode little-endian binary primitives, strings, 
    and custom structures like Quaternions, Vectors, and Identifiers.
    """
    def __init__(self, data_bytes):
        self.stream = io.BytesIO(data_bytes)
        
    def read(self, size):
        return self.stream.read(size)
        
    def tell(self):
        return self.stream.tell()
        
    def seek(self, offset, whence=0):
        return self.stream.seek(offset, whence)
        
    def read_byte(self):
        return struct.unpack('B', self.read(1))[0]
        
    def read_bool(self):
        return struct.unpack('?', self.read(1))[0]
        
    def read_ushort(self):
        return struct.unpack('<H', self.read(2))[0]
        
    def read_short(self):
        return struct.unpack('<h', self.read(2))[0]
        
    def read_uint(self):
        return struct.unpack('<I', self.read(4))[0]
        
    def read_int(self):
        return struct.unpack('<i', self.read(4))[0]
        
    def read_float(self):
        return struct.unpack('<f', self.read(4))[0]
        
    def read_half(self):
        """
        Reads a 16-bit half-precision float ('e' format in python struct).
        This is an IEEE-754 half-precision binary float used widely in GTFOReplay.
        """
        return struct.unpack('<e', self.read(2))[0]
        
    def read_string(self):
        """
        Strings in GTFOReplay are serialized as a 2-byte ushort length 
        followed by UTF-8 bytes.
        """
        length = self.read_ushort()
        return self.read(length).decode('utf-8', errors='ignore')
        
    def read_identifier(self):
        """
        An Identifier is a custom GTFOReplay structure representing items, gear, or enemies.
        Format:
        - 1-byte type (0=Unknown, 1=Gear, 2=Alias_Gear, 3=Item, 4=Enemy, 5=Vanity)
        - Depending on the type:
          - Unknown (0): no extra data
          - Gear (1): string JSON key + ushort alias ID
          - Alias_Gear (2): ushort ID
          - Item, Enemy, Vanity (3, 4, 5): ushort persistentID
        """
        type_val = self.read_byte()
        if type_val == 0:
            return {"type": "Unknown", "id": 0}
        elif type_val == 1:
            string_key = self.read_string()
            id_val = self.read_ushort()
            return {"type": "Gear", "stringKey": string_key, "id": id_val}
        elif type_val == 2:
            id_val = self.read_ushort()
            return {"type": "Alias_Gear", "id": id_val}
        elif type_val in (3, 4, 5):
            id_val = self.read_ushort()
            types = {3: "Item", 4: "Enemy", 5: "Vanity"}
            return {"type": types[type_val], "id": id_val}
        else:
            raise ValueError(f"Unknown Identifier type: {type_val} at position {self.tell()}")


def parse_spawn_bytes(typename, version, reader):
    """
    Simulates the TypeScript 'spawn.parse' logic for each dynamic entity type.
    This reads exactly the correct number of bytes from the binary stream for each
    spawn event, preventing stream misalignment.
    """
    if typename == "Vanilla.Player":
        # DynamicTransform.spawn reads:
        # - 1 byte (dimension)
        # - 12 bytes (Vector3 position)
        # - 7 bytes (HalfQuaternion rotation: 1 byte + 3 half-floats)
        reader.read(20)
        snet = reader.read_uint() | (reader.read_uint() << 32) # read 8-byte Steam ID as uint64
        slot = reader.read_byte()
        nickname = reader.read_string()
        return {"snet": snet, "slot": slot, "nickname": nickname}
        
    elif typename == "ReplayRecorder.Player":
        snet = reader.read_uint() | (reader.read_uint() << 32)
        nickname = reader.read_string()
        return {"snet": snet, "nickname": nickname}
        
    elif typename == "Vanilla.Enemy":
        reader.read(20) # DynamicTransform.spawn (20 bytes)
        anim_handle = reader.read_ushort()
        scale = reader.read_half()
        enemy_type = reader.read_identifier()
        max_health = float('inf')
        if version != "0.0.1":
            max_health = reader.read_half()
        return {"type": enemy_type, "max_health": max_health}
        
    elif typename == "Vanilla.Sentry":
        reader.read(20) # DynamicTransform.spawn (20 bytes)
        if version == "0.0.1":
            owner = reader.read_ushort()
        else:
            has_owner = reader.read_bool()
            if has_owner:
                owner = reader.read_ushort()
        return {}
        
    elif typename == "Vanilla.Mine":
        reader.read(20) # DynamicTransform.spawn (20 bytes)
        if version == "0.0.1":
            item_index = reader.read_byte()
            owner = reader.read_ushort()
            item = {"type": "Item", "id": item_index}
        else:
            item = reader.read_identifier()
            owner = reader.read_ushort()
        return {"item": item, "owner": owner}
        
    elif typename == "Vanilla.Pings":
        slot = reader.read_byte()
        dimension = reader.read_byte()
        reader.read(12) # Vector3 position (12 bytes)
        visible = reader.read_bool()
        style = reader.read_byte()
        return {}
        
    elif typename == "Vanilla.WardenEvents.Survival":
        survival_text = reader.read_string()
        to_activate_text = reader.read_string()
        return {}
        
    elif typename == "Vanilla.Cfoam":
        # DynamicPosition.spawn reads:
        # - 1 byte (dimension)
        # - 12 bytes (Vector3 position)
        reader.read(13)
        scale = reader.read_half()
        return {}
        
    elif typename == "Vanilla.Bioscan":
        reader.read(13) # DynamicPosition.spawn (13 bytes)
        radius = reader.read_half()
        return {}
        
    elif typename == "Vanilla.Bioscan.Status":
        progress = reader.read_byte()
        r = reader.read_byte()
        g = reader.read_byte()
        b = reader.read_byte()
        return {}
        
    elif typename == "Vanilla.Holopath":
        dimension = reader.read_byte()
        length = reader.read_byte()
        reader.read(12) # Vector3 spline[0]
        for _ in range(1, length):
            reader.read(6) # HalfVector point deltas (6 bytes each)
        return {}
        
    elif typename == "Vanilla.FogSphere":
        reader.read(13) # DynamicPosition.spawn (13 bytes)
        range_val = reader.read_half()
        return {}
        
    elif typename == "Vanilla.DynamicItem":
        reader.read(20) # DynamicTransform.spawn (20 bytes)
        item_type = reader.read_identifier()
        return {}
        
    elif typename == "Vanilla.Objectives.Reactor":
        serial_number = reader.read_ushort()
        layer = reader.read_byte()
        master_terminal = reader.read_int()
        num_waves = reader.read_byte()
        for _ in range(num_waves):
            code_terminal_serial = reader.read_ushort()
            code = reader.read_string()
        return {}
        
    elif typename == "Vanilla.Enemy.Spitters.State":
        state = reader.read_byte()
        return {}
        
    elif typename == "Vanilla.Map.Generators.State":
        powered = reader.read_bool()
        return {}
        
    elif typename == "Vanilla.Map.ResourceContainers.State":
        closed = reader.read_bool()
        lock_type = reader.read_byte()
        return {}
        
    elif typename == "Vanilla.Map.Items":
        dimension = reader.read_byte()
        reader.read(12) # Vector3 position
        reader.read(7)  # HalfQuaternion rotation
        on_ground = reader.read_bool()
        linked_to_machine = reader.read_bool()
        player_slot = reader.read_byte()
        serial_number = reader.read_ushort()
        item_id = reader.read_identifier()
        return {}
        
    elif typename == "Vanilla.Map.WeakDoor":
        max_health = reader.read_half()
        lock0 = reader.read_byte()
        lock1 = reader.read_byte()
        return {}
        
    elif typename == "Vanilla.Player.Stats":
        health = reader.read_byte()
        infection = reader.read_byte()
        primary_ammo = reader.read_byte()
        secondary_ammo = reader.read_byte()
        tool_ammo = reader.read_byte()
        consumable_ammo = reader.read_byte()
        resource_ammo = reader.read_byte()
        if version == "0.0.3":
            stamina = reader.read_byte()
        return {}
        
    elif typename == "Vanilla.Player.Backpack":
        for _ in range(8):
            reader.read_identifier()
        if version == "0.0.2":
            for _ in range(5):
                reader.read_identifier()
        return {}
        
    elif typename == "Vanilla.Player.Boosters":
        num_implants = reader.read_byte()
        for _ in range(num_implants):
            implant_id = reader.read_ushort()
            num_effects = reader.read_byte()
            for _ in range(num_effects):
                eff_type = reader.read_byte()
                eff_val = reader.read_half()
            num_conditions = reader.read_byte()
            for _ in range(num_conditions):
                cond = reader.read_byte()
        return {}
        
    elif typename == "Vanilla.Player.Animation":
        # velocity (2) + crouch (1) + targetLookDir (6) + state (1) + meleeCharging (1) + throwCharging (1) + isReloading (1) + reloadDuration (2)
        reader.read(15)
        return {}
        
    elif typename == "Vanilla.Enemy.Animation":
        # velocity (3) + state (1) + up (1) + detect (1)
        reader.read(6)
        return {}
        
    elif typename == "Vanilla.Enemy.LimbCustom":
        owner = reader.read_ushort()
        bone = reader.read_byte()
        offset = reader.read(6) # HalfVector (6 bytes)
        scale = reader.read_half()
        return {}
        
    elif typename == "Vanilla.Enemy.Projectile":
        reader.read(20) # DynamicTransform.spawn (20 bytes)
        return {}
        
    elif typename == "Vanilla.Enemy.Stats":
        tagged = reader.read_bool()
        return {}
        
    elif typename == "Vanilla.Enemy.Tendril":
        sourcePos = reader.read(6) # HalfVector (6 bytes)
        relPos = reader.read(6) # HalfVector (6 bytes)
        detect = reader.read_bool()
        owner = reader.read_ushort()
        return {}
        
    elif typename == "Vanilla.Enemy.Tongue":
        owner = reader.read_ushort()
        dimension = reader.read_byte()
        progress = reader.read_byte()
        length = reader.read_byte()
        spline0 = reader.read(12) # Vector3 (12 bytes)
        for _ in range(1, length):
            reader.read(6) # HalfVector (6 bytes)
        return {}
        
    elif typename == "Vanilla.Enemy.Ragdoll":
        reader.read(20) # DynamicTransform.spawn (20 bytes)
        anim_handle = reader.read_ushort()
        scale = reader.read_half()
        enemy_type = reader.read_identifier()
        max_health = reader.read_half()
        if version == "0.0.1":
            pass # head is hardcoded to true
        else:
            head = reader.read_bool()
        reader.read(108) # 18 joints * 6 bytes HalfVector each
        return {}
        
    elif typename == "EWC.Projectile":
        reader.read(20) # DynamicTransform.spawn (20 bytes)
        slot = reader.read_byte()
        scale = reader.read_half()
        return {}
        
    elif typename == "RagdollMode.Ragdoll":
        # spawn is void (0 bytes)
        return {}
        
    else:
        # Unknown fallback (should not occur for vanilla replays)
        raise ValueError(f"Spawn parser for '{typename}' is not registered.")


def skip_header(typename, version, reader):
    """
    Parses and skips static Header layouts to cleanly proceed through 
    the initial metadata portion of the file.
    """
    if typename == "ReplayRecorder.Header":
        version_str = reader.read_string()
        is_master = reader.read_byte() == 1
        
    elif typename == "Vanilla.Metadata":
        version_str = reader.read_string()
        if version == "0.0.2":
            reader.read_bool()
        elif version == "0.0.3":
            reader.read_bool()
            reader.read_bool()
        elif version == "0.0.4":
            reader.read_bool()
            reader.read_bool()
            reader.read_bool()
            
    elif typename == "Vanilla.Map.Doors":
        n_doors = reader.read_ushort()
        for _ in range(n_doors):
            reader.read_int() # id
            reader.read_byte() # dimension
            reader.read(12) # Vector3 position
            reader.read(7) # HalfQuaternion rotation
            reader.read_ushort() # serialNumber
            reader.read_bool() # isCheckpoint
            reader.read_byte() # type
            reader.read_byte() # size
            
    elif typename == "Vanilla.Map.Ladders":
        n_ladders = reader.read_ushort()
        for _ in range(n_ladders):
            reader.read_byte() # dimension
            reader.read(12) # Vector3 top
            reader.read(7) # HalfQuaternion rotation
            reader.read_half() # height
            
    elif typename == "Vanilla.Map.Terminals":
        n_terminals = reader.read_ushort()
        for _ in range(n_terminals):
            reader.read_int() # id
            reader.read_byte() # dimension
            reader.read(12) # position
            reader.read(7) # rotation
            if version == "0.0.2":
                reader.read_ushort() # serialNumber
                
    elif typename == "Vanilla.Map.Generators":
        n_generators = reader.read_ushort()
        for _ in range(n_generators):
            reader.read_int() # id
            reader.read_byte() # dimension
            reader.read(12) # position
            reader.read(7) # rotation
            reader.read_ushort() # serialNumber
            
    elif typename == "Vanilla.Map.ResourceContainers":
        n_containers = reader.read_ushort()
        for _ in range(n_containers):
            reader.read_int() # id
            reader.read_byte() # dimension
            reader.read(12) # position
            reader.read(7) # rotation
            reader.read_ushort() # serialNumber
            reader.read_bool() # isLocker
            if version in ("0.0.2", "0.0.3"):
                reader.read_identifier() # consumableType
                reader.read_bool() # registered
            if version == "0.0.3":
                reader.read_byte() # assignedLock
                
    elif typename == "Vanilla.Map.DisinfectStations":
        n_stations = reader.read_ushort()
        for _ in range(n_stations):
            reader.read_int() # id
            reader.read_byte() # dimension
            reader.read(12) # position
            reader.read(7) # rotation
            reader.read_ushort() # serialNumber
            
    elif typename == "Vanilla.Map.BulkheadControllers":
        n_controllers = reader.read_ushort()
        for _ in range(n_controllers):
            reader.read_int() # id
            reader.read_byte() # dimension
            reader.read(12) # position
            reader.read(7) # rotation
            reader.read_ushort() # serialNumber
            for _ in range(3): # 3 layers
                connected = reader.read_bool()
                if connected:
                    reader.read_int()
                    
    elif typename == "Vanilla.Enemy.Spitters":
        n_spitters = reader.read_ushort()
        for _ in range(n_spitters):
            reader.read_int() # id
            reader.read_byte() # dimension
            reader.read(12) # position
            reader.read(7) # rotation
            reader.read_half() # scale
            
    elif typename == "Vanilla.Map.Geometry":
        dimension = reader.read_byte()
        n_vertices = reader.read_ushort()
        n_indices = reader.read_uint()
        reader.read(n_vertices * 12) # VectorArray (vertices)
        reader.read(n_indices * 2) # UShortArray (indices)
        
    elif typename == "Vanilla.Map.Geometry.EOH":
        pass
        
    else:
        raise ValueError(f"Unknown Header type '{typename}' encountered.")


def parse_replay_file(filepath):
    """
    Decompresses and parses a single replay file, aggregating player statistics
    and extracting metadata (ID, date, players participating, and match duration).
    """
    print(f"\nProcessing: {os.path.basename(filepath)}")
    
    # 1. Decompress ZIP archive in memory
    try:
        with zipfile.ZipFile(filepath, 'r') as z:
            filename = z.namelist()[0]
            with z.open(filename) as f:
                binary_data = f.read()
    except Exception as e:
        print(f"  Error: Failed to decompress file. {e}")
        return None

    reader = BinaryReader(binary_data)
    
    # 2. Combined Header Size
    header_size = reader.read_int()
    typemap_start = reader.tell()
    
    # 3. Typemap
    typemap_version = reader.read_string()
    if typemap_version != "0.0.1":
        print(f"  Error: Unsupported Typemap version: {typemap_version}")
        return None
        
    num_types = reader.read_ushort()
    typemap = {}
    for _ in range(num_types):
        type_id = reader.read_ushort()
        typename = reader.read_string()
        version = reader.read_string()
        typemap[type_id] = {"typename": typename, "version": version}

    # 4. Headers Loop
    # Read headers until we hit "ReplayRecorder.EndOfHeader"
    while True:
        type_id = reader.read_ushort()
        module = typemap.get(type_id)
        if not module:
            print(f"  Error: Unknown Type ID {type_id} in headers!")
            return None
        if module["typename"] == "ReplayRecorder.EndOfHeader":
            break
        skip_header(module["typename"], module["version"], reader)

    # Move directly past the header section to guarantee we start clean at snapshot loop
    reader.seek(typemap_start + header_size)
    
    # 5. Runtime Tracking Stores
    # Maps entity IDs to runtime details
    player_id_to_snet = {}          # player_id -> snet
    player_snet_to_nick = {}        # snet -> nickname
    mine_id_to_owner_snet = {}      # mine_id -> owner_snet
    enemy_id_to_health = {}         # enemy_id -> current health
    enemy_id_to_type = {}           # enemy_id -> persistent type ID
    
    # Aggregated Player Statistics grouped by Steam ID (snet)
    stats_store = {} # snet -> stats_dict
    
    def get_or_create_player_stats(snet, nickname=None):
        if snet not in stats_store:
            stats_store[snet] = {
                "nickname": nickname or f"SteamId_{snet}",
                "snet": snet,
                "bulletDamage": 0.0,
                "meleeDamage": 0.0,
                "sentryDamage": 0.0,
                "explosiveDamage": 0.0,
                "staggerDamage": 0.0,
                "sentryStaggerDamage": 0.0,
                "playerBulletDamage": 0.0,
                "playerSentryDamage": 0.0,
                "playerExplosiveDamage": 0.0,
                "kills": 0,
                "mineKills": 0,
                "sentryKills": 0,
                "revives": 0,
                "ammoPacksUsed": 0,
                "toolPacksUsed": 0,
                "healthPacksUsed": 0,
                "disinfectPacksUsed": 0,
                "tongueDodges": 0,
                "timesDowned": 0
            }
        elif nickname and stats_store[snet]["nickname"].startswith("SteamId_"):
            stats_store[snet]["nickname"] = nickname
        return stats_store[snet]

    last_timestamp = 0
    total_bytes = len(binary_data)
    
    # 6. Snapshot Timeline Parsing Loop
    # Keep parsing snapshot blocks until EOF
    while reader.tell() < total_bytes:
        snapshot_start = reader.tell()
        try:
            snapshot_size = reader.read_int()
        except struct.error:
            # Reached end of file cleanly
            break
            
        if snapshot_size <= 0:
            break
            
        snapshot_end = snapshot_start + 4 + snapshot_size
        
        # Read the uint millisecond timestamp
        timestamp = reader.read_uint()
        last_timestamp = timestamp
        
        # Parse Events in this snapshot
        num_events = reader.read_int()
        for _ in range(num_events):
            delta = reader.read_ushort()
            type_id = reader.read_ushort()
            module = typemap.get(type_id)
            if not module:
                continue
                
            typename = module["typename"]
            version = module["version"]
            
            # --- Dynamic Spawn Events ---
            if typename == "ReplayRecorder.Spawn":
                spawned_type_id = reader.read_ushort()
                spawned_id = reader.read_int()
                spawned_module = typemap.get(spawned_type_id)
                if spawned_module:
                    res = parse_spawn_bytes(spawned_module["typename"], spawned_module["version"], reader)
                    if spawned_module["typename"] == "Vanilla.Player":
                        player_id_to_snet[spawned_id] = res["snet"]
                        player_snet_to_nick[res["snet"]] = res["nickname"]
                        get_or_create_player_stats(res["snet"], res["nickname"])
                    elif spawned_module["typename"] == "ReplayRecorder.Player":
                        player_snet_to_nick[res["snet"]] = res["nickname"]
                        get_or_create_player_stats(res["snet"], res["nickname"])
                    elif spawned_module["typename"] == "Vanilla.Mine":
                        mine_id_to_owner_snet[spawned_id] = player_id_to_snet.get(res["owner"], 0)
                    elif spawned_module["typename"] == "Vanilla.Enemy":
                        # Store health for kill mapping
                        hp = res["max_health"]
                        if hp == float('inf'):
                            # Fallback if version 0.0.1 or infinite
                            persistent_id = res["type"]["id"]
                            hp = BACKWARDS_COMPAT_ENEMY_HP.get(persistent_id, 42.0)
                        enemy_id_to_health[spawned_id] = hp
                        enemy_id_to_type[spawned_id] = res["type"]["id"]
                        
            # --- Dynamic Despawn Events ---
            elif typename == "ReplayRecorder.Despawn":
                despawned_type_id = reader.read_ushort()
                despawned_id = reader.read_int()
                # void parse despawn (reads 0 bytes)
                
            # --- StatTracker Damage Events ---
            elif typename == "Vanilla.StatTracker.Damage":
                dmg_type_idx = reader.read_byte()
                source_id = reader.read_int()
                target_id = reader.read_ushort()
                damage = reader.read_half()
                gear = reader.read_identifier()
                sentry = reader.read_bool()
                stagger_damage = reader.read_half()
                
                # Damage Types: 0=Bullet, 1=Explosive, 2=Melee, 3=Projectile, 4=Tongue, 5=Fall
                if dmg_type_idx == 0: # Bullet
                    owner_snet = player_id_to_snet.get(source_id)
                    if owner_snet:
                        p_stats = get_or_create_player_stats(owner_snet)
                        if target_id in player_id_to_snet: # Friendly fire on players
                            if sentry:
                                p_stats["playerSentryDamage"] += damage
                            else:
                                p_stats["playerBulletDamage"] += damage
                        else: # Dealt to enemies
                            if sentry:
                                p_stats["sentryDamage"] += damage
                                p_stats["sentryStaggerDamage"] += stagger_damage
                            else:
                                p_stats["bulletDamage"] += damage
                                p_stats["staggerDamage"] += stagger_damage
                                
                            # Check for kill
                            if target_id in enemy_id_to_health:
                                enemy_id_to_health[target_id] -= damage
                                if enemy_id_to_health[target_id] <= 0:
                                    enemy_id_to_health[target_id] = 0
                                    if sentry:
                                        p_stats["sentryKills"] += 1
                                    else:
                                        p_stats["kills"] += 1
                                        
                elif dmg_type_idx == 1: # Explosive (Mines)
                    owner_snet = mine_id_to_owner_snet.get(source_id)
                    if owner_snet:
                        p_stats = get_or_create_player_stats(owner_snet)
                        if target_id in player_id_to_snet:
                            p_stats["playerExplosiveDamage"] += damage
                        else:
                            p_stats["explosiveDamage"] += damage
                            p_stats["staggerDamage"] += stagger_damage
                            
                            # Check for kill
                            if target_id in enemy_id_to_health:
                                enemy_id_to_health[target_id] -= damage
                                if enemy_id_to_health[target_id] <= 0:
                                    enemy_id_to_health[target_id] = 0
                                    p_stats["mineKills"] += 1
                                    
                elif dmg_type_idx == 2: # Melee
                    owner_snet = player_id_to_snet.get(source_id)
                    if owner_snet:
                        p_stats = get_or_create_player_stats(owner_snet)
                        if target_id not in player_id_to_snet: # Melee damage to enemies
                            p_stats["meleeDamage"] += damage
                            p_stats["staggerDamage"] += stagger_damage
                            
                            # Check for kill
                            if target_id in enemy_id_to_health:
                                enemy_id_to_health[target_id] -= damage
                                if enemy_id_to_health[target_id] <= 0:
                                    enemy_id_to_health[target_id] = 0
                                    p_stats["kills"] += 1
                                    
                elif dmg_type_idx == 5: # Fall Damage
                    target_snet = player_id_to_snet.get(target_id)
                    # (Fall damage is taken by players, not dealt to enemies)
                    
            # --- StatTracker PackUse Events ---
            elif typename == "Vanilla.StatTracker.Pack":
                pack_type_idx = reader.read_byte()
                source_id = reader.read_ushort()
                target_id = reader.read_ushort()
                
                target_snet = player_id_to_snet.get(target_id)
                if target_snet:
                    p_stats = get_or_create_player_stats(target_snet)
                    # Pack Types: 0=Ammo, 1=Tool, 2=Healing, 3=Disinfect
                    if pack_type_idx == 0:
                        p_stats["ammoPacksUsed"] += 1
                    elif pack_type_idx == 1:
                        p_stats["toolPacksUsed"] += 1
                    elif pack_type_idx == 2:
                        p_stats["healthPacksUsed"] += 1
                    elif pack_type_idx == 3:
                        p_stats["disinfectPacksUsed"] += 1
                        
            # --- StatTracker Revive Events ---
            elif typename == "Vanilla.StatTracker.Revive":
                source_id = reader.read_ushort()
                target_id = reader.read_ushort()
                owner_snet = player_id_to_snet.get(source_id)
                if owner_snet:
                    p_stats = get_or_create_player_stats(owner_snet)
                    p_stats["revives"] += 1
                    
            # --- StatTracker TongueDodge Events ---
            elif typename == "Vanilla.StatTracker.TongueDodge":
                source_id = reader.read_ushort()
                target_id = reader.read_ushort()
                owner_snet = player_id_to_snet.get(target_id)
                if owner_snet:
                    p_stats = get_or_create_player_stats(owner_snet)
                    p_stats["tongueDodges"] += 1
                    
            # --- Other Events (Skip exactly by reading their serial bytes) ---
            elif typename == "Vanilla.Checkpoint":
                pass
            elif typename == "Vanilla.Player.Gunshots.Info":
                reader.read_int()
                reader.read_identifier()
                reader.read(2)
            elif typename == "Vanilla.Mine.Detonate":
                reader.read_int()
                reader.read_ushort()
                reader.read_bool()
            elif typename == "Vanilla.Enemy.Spitter.Explode":
                reader.read_int()
            elif typename == "Vanilla.Map.DoorStatusChange":
                reader.read_int()
                reader.read_byte()
            elif typename == "Vanilla.Map.WeakDoor.Punch":
                reader.read_int()
            elif typename in (
                "Vanilla.Player.Animation.MeleeSwing", "Vanilla.Player.Animation.MeleeShove",
                "Vanilla.Player.Animation.ConsumableThrow", "Vanilla.Player.Animation.Revive",
                "Vanilla.Player.Animation.Downed"
            ):
                owner_id = reader.read_int()
                if typename == "Vanilla.Player.Animation.MeleeSwing":
                    reader.read_bool()
                
                if typename == "Vanilla.Player.Animation.Downed":
                    owner_snet = player_id_to_snet.get(owner_id)
                    if owner_snet:
                        p_stats = get_or_create_player_stats(owner_snet)
                        p_stats["timesDowned"] += 1
            elif typename == "Vanilla.Player.Gunshots":
                reader.read_int() # owner
                reader.read_byte() # dimension
                reader.read_half() # damage
                reader.read_bool() # sentry
                reader.read(12) # start Vector3
                reader.read(12) # end Vector3
                if version == "0.0.2":
                    reader.read_bool() # silent
            elif typename == "Vanilla.Enemy.Alert":
                reader.read_int() # enemy
                reader.read_byte() # slot
            elif typename == "Vanilla.Enemy.LimbDestruction":
                reader.read_int() # enemy
                reader.read_byte() # limb
            elif typename == "Vanilla.Enemy.Animation.Scream":
                reader.read_int() # enemy
                reader.read_byte() # animIndex
                reader.read_byte() # type
            elif typename == "Vanilla.Enemy.TongueEvent":
                reader.read_int() # enemy/id
                length = reader.read_byte()
                reader.read(12) # spline[0] Vector3
                for _ in range(1, length):
                    reader.read(6) # spline[i] HalfVector
            elif typename == "EWC.Damage":
                reader.read_byte() # type
                reader.read_ushort() # source
                reader.read_ushort() # target
                reader.read_half() # damage
                if version == "0.0.2":
                    reader.read_bool() # isSentry
            elif typename == "EWC.Explosion":
                reader.read(12) # position Vector3
                reader.read_half() # innerRadius
                reader.read_half() # radius
            elif typename in (
                "Vanilla.Enemy.Animation.AttackWindup", "Vanilla.Enemy.Animation.Jump",
                "Vanilla.Enemy.Animation.Heartbeat", "Vanilla.Enemy.Animation.PouncerGrab",
                "Vanilla.Enemy.Animation.PouncerSpit"
            ):
                reader.read_int() # enemy/id
                if typename not in ("Vanilla.Enemy.Animation.PouncerGrab", "Vanilla.Enemy.Animation.PouncerSpit"):
                    reader.read_byte() # animIndex
            elif typename == "Vanilla.Enemy.Animation.Hitreact":
                reader.read_int() # enemy/id
                reader.read_byte() # animIndex
                reader.read_byte() # direction
                reader.read_byte() # type
            elif typename == "Vanilla.Enemy.Animation.Melee":
                reader.read_int() # enemy/id
                reader.read_byte() # animIndex
                reader.read_byte() # type
            elif typename == "Vanilla.Enemy.Animation.Wakeup":
                reader.read_int() # enemy/id
                reader.read_byte() # animIndex
                reader.read_bool() # turn
            elif typename == "Vanilla.Enemy.Animation.ScoutScream":
                reader.read_int() # enemy/id
                reader.read_bool() # start
            elif typename == "Vanilla.Enemy.Animation.BigFlyerCharge":
                reader.read_int() # enemy/id
                reader.read_half() # charge
            else:
                raise ValueError(f"Event parser for '{typename}' is not registered.")
                    
        # Skip Dynamics & pad bytes: seek directly to next snapshot block boundary
        reader.seek(snapshot_end)

    # 7. Compile Metadata Header Information
    # Filename format e.g. R4E1 2026-03-08 19-31.compressed
    basename = os.path.basename(filepath)
    run_id = basename.split(" ")[0] if " " in basename else "UnknownID"
    
    # Try to parse date from filename or fallback
    date_str = "UnknownDate"
    parts = basename.replace(".compressed", "").split(" ")
    if len(parts) >= 3:
        date_str = f"{parts[1]} {parts[2].replace('-', ':')}"
        
    duration_mins = round(last_timestamp / 60000.0, 1)
    
    player_names = sorted(list(player_snet_to_nick.values()))
    player_names_str = ", ".join(player_names)
    
    metadata = {
        "id": run_id,
        "date": date_str,
        "players": player_names_str,
        "duration": duration_mins,
        "filename": basename
    }
    
    return metadata, stats_store


def export_to_csv(metadata, stats_store, output_dir):
    """
    Exports the aggregated per-player summaries to a formatted CSV file 
    with a metadata header line.
    """
    csv_filename = metadata["filename"].replace(".compressed", ".csv")
    csv_filepath = os.path.join(output_dir, csv_filename)
    
    with open(csv_filepath, 'w', newline='', encoding='utf-8') as csvfile:
        # 1. Write identifying metadata header line (prefixed with # for spreadsheet compatibility)
        csvfile.write(f"# Run ID:, {metadata['id']},  Date:, {metadata['date']},  Players:, {metadata['players']},  Duration:, {metadata['duration']}, mins\n")
        
        # 2. Write CSV Data Rows
        writer = csv.writer(csvfile)
        headers = [
            "Player Name", "Steam ID", "Bullet Damage", "Melee Damage", "Sentry Damage", 
            "Explosive Damage", "Total Damage Dealt", "Stagger Damage", "Sentry Stagger Damage",
            "Kills", "Sentry Kills", "Mine Kills", "Total Kills", "Ammo Packs Used", 
            "Tool Packs Used", "Health Packs Used", "Disinfect Packs Used", "Revives", "Downs", "Tongue Dodges"
        ]
        writer.writerow(headers)
        
        for snet, stats in stats_store.items():
            tot_dmg = stats["bulletDamage"] + stats["meleeDamage"] + stats["sentryDamage"] + stats["explosiveDamage"]
            tot_kills = stats["kills"] + stats["sentryKills"] + stats["mineKills"]
            row = [
                stats["nickname"],
                stats["snet"],
                round(stats["bulletDamage"], 1),
                round(stats["meleeDamage"], 1),
                round(stats["sentryDamage"], 1),
                round(stats["explosiveDamage"], 1),
                round(tot_dmg, 1),
                round(stats["staggerDamage"], 1),
                round(stats["sentryStaggerDamage"], 1),
                stats["kills"],
                stats["sentryKills"],
                stats["mineKills"],
                tot_kills,
                stats["ammoPacksUsed"],
                stats["toolPacksUsed"],
                stats["healthPacksUsed"],
                stats["disinfectPacksUsed"],
                stats["revives"],
                stats["timesDowned"],
                stats["tongueDodges"]
            ]
            writer.writerow(row)
            
    print(f"  Success: Exported CSV to {csv_filepath}")
    return csv_filepath


def main():
    # If a specific file is provided as a command line argument, process only that file
    if len(sys.argv) > 1:
        target_file = sys.argv[1]
        if not os.path.exists(target_file):
            print(f"Error: File '{target_file}' not found.")
            sys.exit(1)
        res = parse_replay_file(target_file)
        if res:
            metadata, stats = res
            export_to_csv(metadata, stats, os.path.dirname(target_file) or ".")
    else:
        # Default behavior: Scan Replay Files folder and parse all files
        base_dir = "CSVs" if os.path.exists("CSVs") else "."
        replay_root = os.path.join(".", "Replay Files")
        if not os.path.exists(replay_root):
            print("Error: 'Replay Files' directory not found. Please place compressed replays under 'Replay Files/Unchecked Replays'.")
            sys.exit(1)
            
        # Scan Unchecked Replays folder
        parsed_count = 0
        for sub in ["Unchecked Replays"]:
            sub_path = os.path.join(replay_root, sub)
            if not os.path.exists(sub_path):
                continue
                
            for file in os.listdir(sub_path):
                if file.endswith(".compressed"):
                    file_path = os.path.join(sub_path, file)
                    res = parse_replay_file(file_path)
                    if res:
                        metadata, stats = res
                        export_to_csv(metadata, stats, base_dir)
                        parsed_count += 1
                        
        if parsed_count == 0:
            print("No .compressed files found under 'Replay Files/Unchecked Replays'.")
        else:
            print(f"\nDone! Successfully processed {parsed_count} replay matches.")

if __name__ == "__main__":
    main()
